// <auto-generated />
using System;
using BiztvillCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiztvillCRM.Data.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260329183239_AddJogszabalyColumns")]
    partial class AddJogszabalyColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Ceg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adoszam")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Cim")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Weboldal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Cegek");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Eszkoz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("GyariSzam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GyartoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TelephelyId")
                        .HasColumnType("int");

                    b.Property<string>("Tipus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UgyfelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GyartoId");

                    b.HasIndex("TelephelyId");

                    b.HasIndex("UgyfelId");

                    b.ToTable("Eszkozok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Felhasznalo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Beosztas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CegId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UtolsoBelepes")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CegId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Gyarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Orszag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Weboldal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Gyartok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Hatosag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Cim")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rovidites")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Weboldal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Hatosagok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Hitelesites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("EszkozId")
                        .HasColumnType("int");

                    b.Property<int?>("HatosagId")
                        .HasColumnType("int");

                    b.Property<int>("HitelesitesStatusz")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LejaratDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ugyszam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EszkozId");

                    b.HasIndex("HatosagId");

                    b.ToTable("Hitelesitesek");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Jogszabaly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("HatalyosKezdet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HatalyosVege")
                        .HasColumnType("datetime2");

                    b.Property<string>("Leiras")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Szam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipus")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Jogszabalyok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Kalibracio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bizonyitvany")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Elvegzo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EszkozId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KovetkezoDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Sikeres")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EszkozId");

                    b.ToTable("Kalibraciok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Karbantartas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Elvegzo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EszkozId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KovetkezoDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Leiras")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EszkozId");

                    b.ToTable("Karbantartasok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Kepzes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LejaratDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Resztvevo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Kepzesek");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Meres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eredmeny")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EszkozId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KovetkezoDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MeresStatusz")
                        .HasColumnType("int");

                    b.Property<int>("MeresTipusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EszkozId");

                    b.HasIndex("MeresTipusId");

                    b.ToTable("Meresek");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.MeresTipus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ErvenyessegHonap")
                        .HasColumnType("int");

                    b.Property<string>("Leiras")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MeresTipusok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Tanusitvany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("KiadoDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LejaratDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Szam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UgyfelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UgyfelId");

                    b.ToTable("Tanusitvanyok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Telephely", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Cim")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kapcsolattarto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UgyfelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UgyfelId");

                    b.ToTable("Telephelyek");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Azonosito")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpCim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TelephelyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TelephelyId");

                    b.ToTable("Terminalok");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Ugyfel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adoszam")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<int>("CegId")
                        .HasColumnType("int");

                    b.Property<string>("Cim")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UgyfelTipus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CegId");

                    b.ToTable("Ugyfelek");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Ugyszam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Beerkezett")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Hatarido")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HatosagId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lezart")
                        .HasColumnType("bit");

                    b.Property<string>("Megjegyzes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Szam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Targy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UgyfelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HatosagId");

                    b.HasIndex("UgyfelId");

                    b.ToTable("Ugyszamok");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Eszkoz", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Gyarto", "Gyarto")
                        .WithMany()
                        .HasForeignKey("GyartoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BiztvillCRM.Shared.Models.Telephely", "Telephely")
                        .WithMany()
                        .HasForeignKey("TelephelyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BiztvillCRM.Shared.Models.Ugyfel", "Ugyfel")
                        .WithMany()
                        .HasForeignKey("UgyfelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gyarto");

                    b.Navigation("Telephely");

                    b.Navigation("Ugyfel");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Felhasznalo", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Ceg", "Ceg")
                        .WithMany("Felhasznalok")
                        .HasForeignKey("CegId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Hitelesites", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BiztvillCRM.Shared.Models.Hatosag", "Hatosag")
                        .WithMany()
                        .HasForeignKey("HatosagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eszkoz");

                    b.Navigation("Hatosag");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Kalibracio", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eszkoz");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Karbantartas", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eszkoz");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Meres", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Eszkoz", "Eszkoz")
                        .WithMany()
                        .HasForeignKey("EszkozId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BiztvillCRM.Shared.Models.MeresTipus", "MeresTipus")
                        .WithMany()
                        .HasForeignKey("MeresTipusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eszkoz");

                    b.Navigation("MeresTipus");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Tanusitvany", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Ugyfel", "Ugyfel")
                        .WithMany()
                        .HasForeignKey("UgyfelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ugyfel");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Telephely", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Ugyfel", "Ugyfel")
                        .WithMany("Telephelyek")
                        .HasForeignKey("UgyfelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ugyfel");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Terminal", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Telephely", "Telephely")
                        .WithMany()
                        .HasForeignKey("TelephelyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Telephely");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Ugyfel", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Ceg", "Ceg")
                        .WithMany("Ugyfelek")
                        .HasForeignKey("CegId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Ugyszam", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Hatosag", "Hatosag")
                        .WithMany()
                        .HasForeignKey("HatosagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BiztvillCRM.Shared.Models.Ugyfel", "Ugyfel")
                        .WithMany()
                        .HasForeignKey("UgyfelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hatosag");

                    b.Navigation("Ugyfel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Felhasznalo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Felhasznalo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiztvillCRM.Shared.Models.Felhasznalo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BiztvillCRM.Shared.Models.Felhasznalo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Ceg", b =>
                {
                    b.Navigation("Felhasznalok");

                    b.Navigation("Ugyfelek");
                });

            modelBuilder.Entity("BiztvillCRM.Shared.Models.Ugyfel", b =>
                {
                    b.Navigation("Telephelyek");
                });
#pragma warning restore 612, 618
        }
    }
}
